[platformio]
default_envs = t4s3
boards_dir = boards

[env:t4s3]
platform = espressif32@6.12.0
framework = arduino
board = T-Display-AMOLED
upload_speed = 921600
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
lib_deps =
    xinyuan-lilygo/LilyGo-AMOLED-Series
    lvgl/lvgl @ 8.4.0
    lewisxhe/XPowersLib @ 0.2.7
    lewisxhe/SensorLib @ 0.2.4
    bodmer/TFT_eSPI @ 2.5.31
